# 3.3 CartPoleを離散化してみる

In [1]:
# 使用するパッケージの宣言
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import gym

In [2]:
# 定数の設定
ENV = 'CartPole-v0'  # 使用する課題名
NUM_DIZITIZED = 6  # 各状態の離散値への分割数

In [3]:
# CartPoleを実行してみる
env = gym.make(ENV)  # 実行する課題を設定
observation = env.reset()  # 環境の初期化

/Users/shinnosuke.yata/.pyenv/versions/3.6.5/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [4]:
# 離散化の閾値を求める


def bins(clip_min, clip_max, num):
    '''観測した状態（連続値）を離散値にデジタル変換する閾値を求める'''
    return np.linspace(clip_min, clip_max, num + 1)[1:-1]

In [5]:
np.linspace(-2.4, 2.4, 6 + 1)

array([-2.4, -1.6, -0.8,  0. ,  0.8,  1.6,  2.4])

In [6]:
np.linspace(-2.4, 2.4, 6 + 1)[1:-1]

array([-1.6, -0.8,  0. ,  0.8,  1.6])

In [13]:
# 状態の４変数を一度に離散的に変換する変数
# np.digitize binで設定したグループに振り分けてくれる
# ４つの状態を６進数を用いて一つの数字として返している。
def digitize_state(observation):
    '''観測したobservation状態を、離散値に変換する'''
    cart_pos, cart_v, pole_angle, pole_v = observation
    digitized = [
        np.digitize(cart_pos, bins=bins(-2.4, 2.4, NUM_DIZITIZED)),
        np.digitize(cart_v, bins=bins(-3.0, 3.0, NUM_DIZITIZED)),
        np.digitize(pole_angle, bins=bins(-0.5, 0.5, NUM_DIZITIZED)),
        np.digitize(pole_v, bins=bins(-2.0, 2.0, NUM_DIZITIZED))]
    return sum([x * (NUM_DIZITIZED**i) for i, x in enumerate(digitized)])

In [8]:
digitize_state(observation)

561

In [4]:
a = np.random.rand(100)
a

array([0.09231308, 0.89671113, 0.0353094 , 0.7881895 , 0.18220635,
       0.17492288, 0.78909508, 0.02665684, 0.75094559, 0.28142838,
       0.57394552, 0.57680211, 0.50971976, 0.46910702, 0.36789767,
       0.33290373, 0.45429423, 0.1184483 , 0.71984519, 0.76985143,
       0.81713378, 0.63888163, 0.10513673, 0.7512885 , 0.52636277,
       0.66291407, 0.66968214, 0.27186599, 0.65282858, 0.57659624,
       0.39240759, 0.40568956, 0.83808909, 0.10426298, 0.84647216,
       0.76337688, 0.71643091, 0.98019988, 0.19215284, 0.95153166,
       0.76604967, 0.41613741, 0.27719081, 0.46035493, 0.80246013,
       0.3393707 , 0.83915624, 0.38564219, 0.52054669, 0.22044536,
       0.59095319, 0.94390242, 0.38794812, 0.78257874, 0.91288188,
       0.70729895, 0.29308088, 0.91415436, 0.01238249, 0.09311162,
       0.72921027, 0.26265334, 0.6806531 , 0.09891163, 0.47130404,
       0.67248659, 0.62553112, 0.53283683, 0.67617224, 0.53851198,
       0.1780559 , 0.14165572, 0.88312393, 0.57671502, 0.40954

In [10]:
b = np.linspace(0,1,11)
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.digitize(a, bins=b)

array([ 1,  9,  1,  8,  2,  2,  8,  1,  8,  3,  6,  6,  6,  5,  4,  4,  5,
        2,  8,  8,  9,  7,  2,  8,  6,  7,  7,  3,  7,  6,  4,  5,  9,  2,
        9,  8,  8, 10,  2, 10,  8,  5,  3,  5,  9,  4,  9,  4,  6,  3,  6,
       10,  4,  8, 10,  8,  3, 10,  1,  1,  8,  3,  7,  1,  5,  7,  7,  6,
        7,  6,  2,  2,  9,  6,  5,  3,  3,  1,  8,  3,  2,  8,  2,  3,  6,
        4,  4,  9,  8,  6,  5,  3,  1,  6,  4,  2,  9,  3,  8,  3])

In [14]:
6**4

1296